package cn.et.food.entity;


public class Food {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOOD.FOODID
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    private Integer foodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOOD.TYPEID
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOOD.FOODNAME
     *F
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    private String foodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOOD.PRICE
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOOD.PATH
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOOD.INTRODUCE
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    private String introduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOOD.FOODID
     *
     * @return the value of FOOD.FOODID
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public Integer getFoodid() {
        return foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOOD.FOODID
     *
     * @param foodid the value for FOOD.FOODID
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public void setFoodid(Integer foodid) {
        this.foodid = foodid;
    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOOD.TYPEID
     *
     * @return the value of FOOD.TYPEID
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOOD.TYPEID
     *
     * @param typeid the value for FOOD.TYPEID
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOOD.FOODNAME
     *
     * @return the value of FOOD.FOODNAME
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOOD.FOODNAME
     *
     * @param foodname the value for FOOD.FOODNAME
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname == null ? null : foodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOOD.PRICE
     *
     * @return the value of FOOD.PRICE
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOOD.PRICE
     *
     * @param price the value for FOOD.PRICE
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOOD.PATH
     *
     * @return the value of FOOD.PATH
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOOD.PATH
     *
     * @param path the value for FOOD.PATH
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOOD.INTRODUCE
     *
     * @return the value of FOOD.INTRODUCE
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOOD.INTRODUCE
     *
     * @param introduce the value for FOOD.INTRODUCE
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }
}