package cn.et.food.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

import cn.et.food.entity.Food;
import cn.et.food.entity.FoodExample;
import cn.et.food.entity.FoodExample.Criteria;
import cn.et.food.entity.FoodExample.Criterion;

public class FoodSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public String countByExample(FoodExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("FOOD");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public String deleteByExample(FoodExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("FOOD");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public String insertSelective(Food record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("FOOD");
        
        if (record.getFoodid() != null) {
            sql.VALUES("FOODID", "#{foodid,jdbcType=DECIMAL}");
        }
        
        if (record.getTypeid() != null) {
            sql.VALUES("TYPEID", "#{typeid,jdbcType=DECIMAL}");
        }
        
        if (record.getFoodname() != null) {
            sql.VALUES("FOODNAME", "#{foodname,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("PRICE", "#{price,jdbcType=DECIMAL}");
        }
        
        if (record.getPath() != null) {
            sql.VALUES("PATH", "#{path,jdbcType=VARCHAR}");
        }
        
        if (record.getIntroduce() != null) {
            sql.VALUES("INTRODUCE", "#{introduce,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public String selectByExample(FoodExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("FOODID");
        } else {
            sql.SELECT("FOODID");
        }
        sql.SELECT("TYPEID");
        sql.SELECT("FOODNAME");
        sql.SELECT("PRICE");
        sql.SELECT("PATH");
        sql.SELECT("INTRODUCE");
        sql.FROM("FOOD");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Food record = (Food) parameter.get("record");
        FoodExample example = (FoodExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("FOOD");
        
        if (record.getFoodid() != null) {
            sql.SET("FOODID = #{record.foodid,jdbcType=DECIMAL}");
        }
        
        if (record.getTypeid() != null) {
            sql.SET("TYPEID = #{record.typeid,jdbcType=DECIMAL}");
        }
        
        if (record.getFoodname() != null) {
            sql.SET("FOODNAME = #{record.foodname,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("PRICE = #{record.price,jdbcType=DECIMAL}");
        }
        
        if (record.getPath() != null) {
            sql.SET("PATH = #{record.path,jdbcType=VARCHAR}");
        }
        
        if (record.getIntroduce() != null) {
            sql.SET("INTRODUCE = #{record.introduce,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("FOOD");
        
        sql.SET("FOODID = #{record.foodid,jdbcType=DECIMAL}");
        sql.SET("TYPEID = #{record.typeid,jdbcType=DECIMAL}");
        sql.SET("FOODNAME = #{record.foodname,jdbcType=VARCHAR}");
        sql.SET("PRICE = #{record.price,jdbcType=DECIMAL}");
        sql.SET("PATH = #{record.path,jdbcType=VARCHAR}");
        sql.SET("INTRODUCE = #{record.introduce,jdbcType=VARCHAR}");
        
        FoodExample example = (FoodExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    public String updateByPrimaryKeySelective(Food record) {
        SQL sql = new SQL();
        sql.UPDATE("FOOD");
        
        if (record.getTypeid() != null) {
            sql.SET("TYPEID = #{typeid,jdbcType=DECIMAL}");
        }
        
        if (record.getFoodname() != null) {
            sql.SET("FOODNAME = #{foodname,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("PRICE = #{price,jdbcType=DECIMAL}");
        }
        
        if (record.getPath() != null) {
            sql.SET("PATH = #{path,jdbcType=VARCHAR}");
        }
        
        if (record.getIntroduce() != null) {
            sql.SET("INTRODUCE = #{introduce,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("FOODID = #{foodid,jdbcType=DECIMAL}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    protected void applyWhere(SQL sql, FoodExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}