package cn.et.food.dao;

import java.lang.Integer;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import cn.et.food.entity.Food;
import cn.et.food.entity.FoodExample;

public interface FoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @SelectProvider(type=FoodSqlProvider.class, method="countByExample")
    long countByExample(FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @DeleteProvider(type=FoodSqlProvider.class, method="deleteByExample")
    int deleteByExample(FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @Delete({
        "delete from FOOD",
        "where FOODID = #{foodid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer foodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @Insert({
        "insert into FOOD (FOODID, TYPEID, ",
        "FOODNAME, PRICE, ",
        "PATH, INTRODUCE)",
        "values (#{foodid,jdbcType=INTEGER}, #{typeid,jdbcType=INTEGER}, ",
        "#{foodname,jdbcType=VARCHAR}, #{price,jdbcType=INTEGER}, ",
        "#{path,jdbcType=VARCHAR}, #{introduce,jdbcType=VARCHAR})"
    })
    int insert(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @InsertProvider(type=FoodSqlProvider.class, method="insertSelective")
    int insertSelective(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @SelectProvider(type=FoodSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="FOODID", property="foodid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TYPEID", property="typeid", jdbcType=JdbcType.INTEGER),
        @Result(column="FOODNAME", property="foodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="PATH", property="path", jdbcType=JdbcType.VARCHAR),
        @Result(column="INTRODUCE", property="introduce", jdbcType=JdbcType.VARCHAR)
    })
    List<Food> selectByExampleWithRowbounds(FoodExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @SelectProvider(type=FoodSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="FOODID", property="foodid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TYPEID", property="typeid", jdbcType=JdbcType.INTEGER),
        @Result(column="FOODNAME", property="foodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="PATH", property="path", jdbcType=JdbcType.VARCHAR),
        @Result(column="INTRODUCE", property="introduce", jdbcType=JdbcType.VARCHAR)
    })
    List<Food> selectByExample(FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @Select({
        "select",
        "FOODID, TYPEID, FOODNAME, PRICE, PATH, INTRODUCE",
        "from FOOD",
        "where FOODID = #{foodid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="FOODID", property="foodid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="TYPEID", property="typeid", jdbcType=JdbcType.INTEGER),
        @Result(column="FOODNAME", property="foodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="PATH", property="path", jdbcType=JdbcType.VARCHAR),
        @Result(column="INTRODUCE", property="introduce", jdbcType=JdbcType.VARCHAR)
    })
    Food selectByPrimaryKey(Integer foodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @UpdateProvider(type=FoodSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Food record, @Param("example") FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @UpdateProvider(type=FoodSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Food record, @Param("example") FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @UpdateProvider(type=FoodSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOOD
     *
     * @mbg.generated Mon Dec 11 09:02:37 CST 2017
     */
    @Update({
        "update FOOD",
        "set TYPEID = #{typeid,jdbcType=INTEGER},",
          "FOODNAME = #{foodname,jdbcType=VARCHAR},",
          "PRICE = #{price,jdbcType=INTEGER},",
          "PATH = #{path,jdbcType=VARCHAR},",
          "INTRODUCE = #{introduce,jdbcType=VARCHAR}",
        "where FOODID = #{foodid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Food record);
}